name: usak_seramik_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_carousel_widget: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.15
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.3.0
  http: ^0.13.6
  image: ^4.0.17
  intl: ^0.17.0
  lottie: ^2.0.0
  mask_text_input_formatter: ^2.5.0
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.15
  photo_view: ^0.14.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  simple_shadow: ^0.3.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.9.3
  webview_flutter_wkwebview: ^3.7.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - i18n/
    - assets/animation/
    - assets/icon/
    - assets/image/
    - assets/dummy/
    - assets/flag/
    - assets/data/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/Avenir.ttc
    - family: Futura
      fonts:
        - asset: assets/font/Futura.ttc
    - family: Helvetica
      fonts:
        - asset: assets/font/Helvetica.ttc
    - family: TimesNewRoman
      fonts:
        - asset: assets/font/TimesNewRoman.ttf
    - family: RaptorV2
      fonts:
        - asset: assets/font/RaptorV2.ttf
    - family: Micro
      fonts:
        - asset: assets/font/Micro.otf
    - family: Oswald
      fonts:
        - asset: assets/font/Oswald.ttf