-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfOVAc06+ikA1GUIT
aonCdI9iyHckT9ORwiZJd2TBS9egCgYIKoZIzj0DAQehRANCAAQix9OYQLIhdfSN
6NgHSGjxzlnfHrMahUSM2V8gvYjQhUa01e02+qAYWV6f8tRxEHotxtK6xhpJQUSN
DxWdDRCF
-----END PRIVATE KEY-----